language: python
sudo: required
install: true
script:
 - debian/test.sh
addons:
  apt:
    packages:
    - build-essential
    - realpath
    - devscripts
    - python-setuptools
    - python-all
    - unzip
    - debconf
    - bash
    - wget
    - dh-exec
    - gdebi
    - python-psutil
